Update patch set 15
Patch Set 15: Code-Review-2

Please fix the testcase basic_network.
    All exceptions should be caught by the testcase instead!
  
    Traceback (most recent call last):
      File "/usr/lib/python3.8/site-packages/xtesting/ci/run_tests.py", line 178, in run_test
        test_case.clean()
      File "/usr/lib/python3.8/site-packages/onaptests/scenario/basic_network.py", line 62, in clean
        self.test.reports_collection.generate_report()
      File "/usr/lib/python3.8/site-packages/onaptests/steps/reports_collection.py", line 103, in generate_report
        report_dict['steps'].sort(key=lambda step: int(''.join(filter(str.isdigit, step['description']))))
      File "/usr/lib/python3.8/site-packages/onaptests/steps/reports_collection.py", line 103, in <lambda>
        report_dict['steps'].sort(key=lambda step: int(''.join(filter(str.isdigit, step['description']))))
    ValueError: invalid literal for int() with base 10: ''

Error on code. It breaks

Patch-set: 15
Reviewer: Gerrit User 6079 <6079@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-2