Update patch set 2
Patch Set 2: Code-Review-1

applicative errors seen in gate

for basic_cnf: https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/1679396577
no results pushed because exception
see 
   File "/usr/lib/python3.8/site-packages/onaptests/scenario/basic_cnf.py", line 10, in <module>
        from onaptests.steps.instantiate.vf_module_ala_carte import YamlTemplateVfModuleAlaCarteInstantiateStep
      File "/usr/lib/python3.8/site-packages/onaptests/steps/instantiate/vf_module_ala_carte.py", line 8, in <module>
        from onapsdk.so.instantiation import VnfParameter
    ImportError: cannot import name 'VnfParameter' from 'onapsdk.so.instantiation' (/usr/lib/python3.8/site-packages/onapsdk/so/instantiation.py)

for basic_vm: https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/1679376517
same 
      File "/usr/lib/python3.8/site-packages/onaptests/scenario/basic_vm.py", line 10, in <module>
        from onaptests.steps.instantiate.vf_module_ala_carte import YamlTemplateVfModuleAlaCarteInstantiateStep
      File "/usr/lib/python3.8/site-packages/onaptests/steps/instantiate/vf_module_ala_carte.py", line 8, in <module>
        from onapsdk.so.instantiation import VnfParameter
    ImportError: cannot import name 'VnfParameter' from 'onapsdk.so.instantiation' (/usr/lib/python3.8/site-packages/onapsdk/so/instantiation.py)

tests to be aligned in pythonsdk tests

Patch-set: 2
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1